spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/powerflow_test
    username: powerflow
    password: powerflow123
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379

persistence:
  type: memory
